apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  # we must provide a selector that is going to properly select our deployment
  selector:
    component: web
  ports:
    # configure the ports that the ClusterIp service is going to expose
    - port: 3000
      targetPort: 3000